### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by ericxtang** [NebulousLabs/skynet-webportal#96]
I tried to follow the steps in `/setup_scripts`, and got the following error when I ran `setup.sh`.

My environment: Ubuntu 18.04, golang v1.13.7

```
go1.13.7.linux-amd64.tar.gz  100%[=============================================>] 114.51M   343MB/s    in 0.3s    
2020-03-19 02:09:17 (343 MB/s) - ‘go1.13.7.linux-amd64.tar.gz’ saved [120071076/120071076]
go version go1.13.7 linux/amd64
Cloning into 'Sia'...
warning: redirecting to https://gitlab.com/NebulousLabs/Sia.git/
remote: Enumerating objects: 4926, done.
remote: Counting objects: 100% (4926/4926), done.
remote: Compressing objects: 100% (548/548), done.
remote: Total 105869 (delta 4621), reused 4583 (delta 4351), pack-reused 100943
Receiving objects: 100% (105869/105869), 32.84 MiB | 25.36 MiB/s, done.
Resolving deltas: 100% (83087/83087), done.
Note: checking out 'v1.4.3'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at 06cb138d3 Merge remote-tracking branch 'origin/siamux-directory-fix' into skynet-prod-v143
go install -tags='netgo' -ldflags='-s -w -X gitlab.com/NebulousLabs/Sia/build.GitRevision=06cb138d3 -X "gitlab.com/
NebulousLabs/Sia/build.BuildTime=Thu Mar 19 02:09:26 UTC 2020"' ./cmd/siac ./cmd/siad
go: downloading gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: downloading gitlab.com/NebulousLabs/fastrand v0.0.0-20181126182046-603482d69e40
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gitlab.com/NebulousLabs/siamux v0.0.0-20200210134842-f0a0c6f85ec7
go: downloading golang.org/x/crypto v0.0.0-20200208060501-ecb85df21340
go: downloading gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: downloading gitlab.com/NebulousLabs/errors v0.0.0-20171229012116-7ead97ef90b8
go: downloading gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: extracting gitlab.com/NebulousLabs/fastrand v0.0.0-20181126182046-603482d69e40
go: downloading gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: extracting gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: extracting github.com/spf13/cobra v0.0.5
go: extracting gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: extracting gitlab.com/NebulousLabs/siamux v0.0.0-20200210134842-f0a0c6f85ec7
go: downloading gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: extracting gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: downloading golang.org/x/text v0.3.0
go: extracting gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: extracting gitlab.com/NebulousLabs/errors v0.0.0-20171229012116-7ead97ef90b8
go: downloading gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: extracting gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: downloading github.com/pkg/errors v0.9.1
go: extracting gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: downloading github.com/hanwen/go-fuse v1.0.0
go: extracting github.com/hanwen/go-fuse v1.0.0
go: extracting golang.org/x/crypto v0.0.0-20200208060501-ecb85df21340
go: extracting github.com/pkg/errors v0.9.1
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/hanwen/go-fuse/v2 v2.0.2
go: extracting github.com/cpuguy83/go-md2man v1.0.10
go: downloading gitlab.com/NebulousLabs/merkletree v0.0.0-20200118113624-07fbf710afc4
go: finding gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: finding gitlab.com/NebulousLabs/bolt v1.4.0
go: finding golang.org/x/text v0.3.0
go: finding gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: finding github.com/pkg/errors v0.9.1
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding gitlab.com/NebulousLabs/siamux v0.0.0-20200210134842-f0a0c6f85ec7
go: finding gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: finding github.com/hanwen/go-fuse/v2 v2.0.2
go: finding github.com/julienschmidt/httprouter v1.3.0
go: finding gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: finding gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: finding github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: finding github.com/klauspost/reedsolomon v1.9.3
go: finding gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: finding github.com/klauspost/cpuid v1.2.2
go: finding gitlab.com/NebulousLabs/monitor v0.0.0-20191205095550-2b0fd3e1012a
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
# runtime/internal/atomic
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:18:6: Load redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:24:6: Loadp redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Load64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:28:26
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: LoadAcq redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:34:27
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:41:6: Xadd redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:39:37
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:44:6: Xadd64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:42:39
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:47:6: Xadduintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:45:47
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:50:6: Xchg redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:48:36
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:53:6: Xchg64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:51:38
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: Xchguintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: too many errors
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/intrinsics_common.go:28:5: ntz8tab redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:58:5
/usr/local/go/src/runtime/internal/sys/intrinsics_common.go:108:7: deBruijn64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:11:20
Makefile:145: recipe for target 'release' failed
make: *** [release] Error 2
```

When I try to run `./setup.sh` again, I get:
```
yarn is already the newest version (1.22.4-1).
The following packages were automatically installed and are no longer required:
  grub-pc-bin libnuma1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
--2020-03-19 17:28:01--  https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4885 (4.8K) [text/plain]
Saving to: ‘alacritty.info’
alacritty.info                                        100%[========================================================================================================================>]   4.77K  --.-KB/s    in 0s      
2020-03-19 17:28:01 (67.9 MB/s) - ‘alacritty.info’ saved [4885/4885]
"alacritty.info", line 18, col 21, terminal 'alacritty-direct': limiting value of `colors' from 0x1000000 to 0x7fff
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
ln: failed to create symbolic link '/etc/nginx/sites-enabled/skynet': File exists
```

**Comment by DavidVorick** [comment]
This does not look like an error to me, it looks like `go get` fetched all the required dependencies.

**Comment by ericxtang** [comment]
Oops - apologize for the copy-and-paste error.  Updated with the full text.

**Comment by kwypchlo** [comment]
The error you're getting running it for the second time is connected to the setup script trying to create a symlink where one is already in place. I have addressed this in #98

**Comment by ericxtang** [comment]
Thanks.  I pulled the latest changes and re-ran `setup.sh`, and now I get:
```
Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease                                   
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease                                 
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                 
Hit:5 https://deb.nodesource.com/node_13.x bionic InRelease                                                       
Hit:6 https://dl.yarnpkg.com/debian stable InRelease                                                              
Hit:7 http://archive.canonical.com/ubuntu bionic InRelease              
Reading package lists... Done                     
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

ps - any idea why the first run is not working?  Seems like a compilation error.

As of now, I'm still unable to set up a portal.

**Comment by DavidVorick** [comment]
`dpkg` errors typically indicate that multiple threads are calling `apt-get install` at the same time, or similar. Is it possible that you were installing something elsewhere at the same time, which caused the script to fail?

**Comment by ericxtang** [comment]
Hi @DavidVorick - I'm less concerned about the `dpkg` errors, since I can just get a new VM and start from scratch.  

I'm more concerned about the initial error that happens when I run `setup.sh` on a new VM. It looks like some kind of dependency problem...
```
go: finding gitlab.com/NebulousLabs/monitor v0.0.0-20191205095550-2b0fd3e1012a
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
# runtime/internal/atomic
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:18:6: Load redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:24:6: Loadp redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Load64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:28:26
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: LoadAcq redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:34:27
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:41:6: Xadd redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:39:37
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:44:6: Xadd64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:42:39
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:47:6: Xadduintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:45:47
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:50:6: Xchg redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:48:36
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:53:6: Xchg64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:51:38
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: Xchguintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: too many errors
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/intrinsics_common.go:28:5: ntz8tab redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:58:5
/usr/local/go/src/runtime/internal/sys/intrinsics_common.go:108:7: deBruijn64 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/sys/intrinsics.go:11:20
Makefile:145: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by kwypchlo** [comment]
Step `make --directory ~/Sia` worked for me just fine when ran on an empty ubuntu docker container.

```
go install -tags='netgo' -ldflags='-s -w -X gitlab.com/NebulousLabs/Sia/build.GitRevision=01f2c0467 -X "gitlab.com/NebulousLabs/Sia/build.BuildTime=Mon Mar 23 23:02:24 CET 2020"' ./cmd/siac ./cmd/siad
go: downloading golang.org/x/crypto v0.0.0-20200117160349-530e935923ad
go: downloading gitlab.com/NebulousLabs/bolt v1.4.0
go: downloading gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: downloading github.com/dchest/threefish v0.0.0-20120919164726-3ecf4c494abf
go: downloading gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: downloading gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: downloading gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: downloading gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: downloading gitlab.com/NebulousLabs/errors v0.0.0-20171229012116-7ead97ef90b8
go: extracting github.com/dchest/threefish v0.0.0-20120919164726-3ecf4c494abf
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: extracting gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: extracting gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: downloading gitlab.com/NebulousLabs/monitor v0.0.0-20191205095550-2b0fd3e1012a
go: downloading gitlab.com/NebulousLabs/siamux v0.0.0-20200217153321-94516948dae2
go: extracting gitlab.com/NebulousLabs/errors v0.0.0-20171229012116-7ead97ef90b8
go: extracting gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: downloading gitlab.com/NebulousLabs/fastrand v0.0.0-20181126182046-603482d69e40
go: extracting gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: extracting gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: downloading github.com/spf13/cobra v0.0.5
go: extracting gitlab.com/NebulousLabs/bolt v1.4.0
go: extracting gitlab.com/NebulousLabs/monitor v0.0.0-20191205095550-2b0fd3e1012a
go: extracting gitlab.com/NebulousLabs/fastrand v0.0.0-20181126182046-603482d69e40
go: extracting gitlab.com/NebulousLabs/siamux v0.0.0-20200217153321-94516948dae2
go: downloading github.com/hanwen/go-fuse v1.0.0
go: extracting github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: extracting github.com/spf13/cobra v0.0.5
go: downloading github.com/spf13/pflag v1.0.3
go: extracting github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: extracting gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: downloading golang.org/x/text v0.3.0
go: extracting github.com/spf13/pflag v1.0.3
go: extracting github.com/hanwen/go-fuse v1.0.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading github.com/hanwen/go-fuse/v2 v2.0.2
go: extracting golang.org/x/crypto v0.0.0-20200117160349-530e935923ad
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading gitlab.com/NebulousLabs/merkletree v0.0.0-20200118113624-07fbf710afc4
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: downloading github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: extracting github.com/klauspost/cpuid v1.2.2
go: downloading github.com/pkg/errors v0.9.1
go: extracting github.com/cpuguy83/go-md2man v1.0.10
go: extracting github.com/hanwen/go-fuse/v2 v2.0.2
go: extracting github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/julienschmidt/httprouter v1.3.0
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: extracting github.com/pkg/errors v0.9.1
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting gitlab.com/NebulousLabs/merkletree v0.0.0-20200118113624-07fbf710afc4
go: extracting golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: extracting github.com/russross/blackfriday v1.5.2
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: extracting golang.org/x/text v0.3.0
go: finding gitlab.com/NebulousLabs/errors v0.0.0-20171229012116-7ead97ef90b8
go: finding github.com/spf13/cobra v0.0.5
go: finding gitlab.com/NebulousLabs/fastrand v0.0.0-20181126182046-603482d69e40
go: finding golang.org/x/crypto v0.0.0-20200117160349-530e935923ad
go: finding gitlab.com/NebulousLabs/entropy-mnemonics v0.0.0-20181018051301-7532f67e3500
go: finding github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: finding github.com/cpuguy83/go-md2man v1.0.10
go: finding gitlab.com/NebulousLabs/bolt v1.4.0
go: finding github.com/dchest/threefish v0.0.0-20120919164726-3ecf4c494abf
go: finding github.com/spf13/pflag v1.0.3
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/pkg/errors v0.9.1
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding golang.org/x/text v0.3.0
go: finding github.com/julienschmidt/httprouter v1.3.0
go: finding gitlab.com/NebulousLabs/siamux v0.0.0-20200217153321-94516948dae2
go: finding gitlab.com/NebulousLabs/merkletree v0.0.0-20200118113624-07fbf710afc4
go: finding github.com/russross/blackfriday v1.5.2
go: finding gitlab.com/NebulousLabs/demotemutex v0.0.0-20151003192217-235395f71c40
go: finding github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: finding gitlab.com/NebulousLabs/ratelimit v0.0.0-20191111145210-66b93e150b27
go: finding gitlab.com/NebulousLabs/go-upnp v0.0.0-20181011194642-3a71999ed0d3
go: finding gitlab.com/NebulousLabs/monitor v0.0.0-20191205095550-2b0fd3e1012a
go: finding gitlab.com/NebulousLabs/writeaheadlog v0.0.0-20190814160017-69f300e9bcb8
go: finding gitlab.com/NebulousLabs/threadgroup v0.0.0-20180716154133-88a11db9e46c
go: finding github.com/hanwen/go-fuse/v2 v2.0.2
go: finding github.com/klauspost/reedsolomon v1.9.3
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: finding github.com/klauspost/cpuid v1.2.2
make: Leaving directory '/root/Sia'
```

Can you paste what `go version` prints for you?

**Comment by ericxtang** [comment]
```
eric@sia-test1:~$ go version
go version go1.13.7 linux/amd64
```

**Comment by lukechampine** [comment]
This type of error can happen when two versions of Go are installed on top of each other. Try wiping your GOROOT (`/usr/local/go`) and reinstalling Go.

This can probably be fixed by having the setup script `rm -rf /usr/local/go` before running the tar command.

**Comment by ericxtang** [comment]
You are right!  I installed go before running `setup.sh`, not knowing it will install its own version of go.  Thanks!
